import { Box, CssBaseline } from '@mui/material';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import 'swiper/css';
// import 'swiper/css/navigation';
// import 'swiper/css/pagination';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <CssBaseline />
      <body className={inter.className}>
        <Box sx={{ bgcolor: 'pink' }}>Header</Box>
        <main>{children}</main>
      </body>
    </html>
  );
}
